
-- 追加插入银行信息
insert into HCPDW.dbo.BANK_DIM_BANK
	(BANK_UID, BANK_NAME, ORIG_BANK_NAME, BANK_LOCATION, REMARK, SOURCE_CODE, SOURCE_ID, UPDATE_DATE, UPDATE_BY, ENABLED)	
select 
	NEWID() as BANK_ID, b.BANK_NAME, b.BANK_NAME as ORIG_BANK_NAME, B.MAX_BANK_LOCATION AS BANK_LOCATION, null as REMARK, 'ORIG_SYSTEM' AS SOURCE_CODE, B.MIN_ACCOUNT_ID AS SOURCE_ID, B.MIN_UPDATE_DATE AS UPDATE_DATE, 'ORIG_USER' as UPDATE_BY, 1 AS ENABLED
from (
	SELECT BANK_NAME, MAX(BANK_LOCATION) AS MAX_BANK_LOCATION, MIN(ID_NO) AS MIN_ACCOUNT_ID, min(Updated_Date) as MIN_UPDATE_DATE
	FROM HCPODS.BANK.T_BANK
	GROUP BY BANK_NAME
) as b
where 1=1
and not exists(
	select 1 from HCPDW.dbo.BANK_DIM_BANK t where t.ORIG_BANK_NAME = b.BANK_NAME 
)
;


-- 追加插入账户信息
insert into HCPDW.dbo.BANK_DIM_BANK_ACCOUNT
	(ACCOUNT_UID, ACCOUNT_NUMBER, LEDGER_NAME, REMARK, BANK_UID, ORIG_COMPANY, ORIG_BANK_NAME, SOURCE_CODE, SOURCE_ID, UPDATE_DATE, UPDATE_BY, ENABLED)
SELECT newid() as ACCOUNT_UID, T.ACCOUNT_NUMBER, cmp.LEDGER_NAME, NULL AS REMARK, B.BANK_UID, T.COMPANY AS ORIG_COMPANY, T.BANK_NAME AS ORIG_BANK_NAME
	, 'ORIG_SYSTEM' AS SOURCE_CODE, MIN(T.ID_NO) AS SOURCE_ID, MIN(T.Updated_Date) AS UPDATE_DATE, 'ORIG_USER' as UPDATE_BY, 1 AS ENABLED
FROM HCPODS.BANK.T_BANK T
INNER JOIN HCPDW.DBO.BANK_DIM_BANK B ON B.ORIG_BANK_NAME = T.BANK_NAME
INNER JOIN HCPODS.bank.T_COMPANY_MAPPING cmp on cmp.BANK_COMPANY = t.Company
WHERE 1=1
AND NOT EXISTS(
	select 1 from HCPDW.dbo.BANK_DIM_BANK_ACCOUNT a where a.ACCOUNT_NUMBER = t.Account_Number
)
GROUP BY T.ACCOUNT_NUMBER, cmp.LEDGER_NAME, T.COMPANY, T.BANK_NAME, B.BANK_UID
;


-- 插入账户用途信息
insert into HCPDW.DBO.BANK_DIM_ACCOUNT_USE
	(USE_UID, ACCOUNT_TYPE, CURRENCY, ACCOUNT_UID, REMARK, ORIG_ACCOUNT_TYPE, ORIG_REMARK, SOURCE_CODE, SOURCE_ID, UPDATE_DATE, UPDATE_BY, ENABLED)
SELECT newid() as USE_UID, lk.MEANING as ACCOUNT_TYPE, replace(T.CURRENCY,'PESO','MXN') AS CURRENCY, BA.ACCOUNT_UID, null as REMARK
	, T.ACCOUNT_TYPE as ORIG_ACCOUNT_TYPE, CONCAT(T.REMARK1,'; ',T.REMARK1,'; ',T.REMARK3) AS ORIG_REMARK
	, 'ORIG_SYSTEM' AS SOURCE_CODE, T.ID_NO AS SOURCE_ID, T.UPDATED_DATE AS UPDATE_DATE, 'ORIG_USER' AS UPDATE_BY, 1 AS ENABLED
FROM HCPODS.BANK.T_BANK T
INNER JOIN HCPDW.DBO.BANK_DIM_BANK_ACCOUNT BA ON BA.ACCOUNT_NUMBER = T.ACCOUNT_NUMBER
left join HCPDW.dbo.FIN_DIM_CUX_LOOKUPS lk on lk.LOOKUP_TYPE = 'BANK_ACCOUNT_TYPE' AND lk.LOOKUP_CODE = t.Account_Type
where 1=1
and not exists(select 1 from HCPDW.DBO.BANK_DIM_ACCOUNT_USE u where u.SOURCE_CODE = 'ORIG_SYSTEM' and u.SOURCE_ID = t.ID_No)
ORDER BY 1,2,3
;


-- 插入账户余额记录
insert into hcpdw.dbo.BANK_FACT_ACCOUNT_BALANCE
	( BALANCE_DATE, BALANCE_AMOUNT, USE_UID, REMARK, SOURCE_CODE, SOURCE_ID, UPDATE_DATE, UPDATE_BY)
SELECT CAST(BB.BALANCE_DATE AS DATE) AS BALANCE_DATE, cast(BB.BALANCE_AMOUNT as numeric(38,5)) as BALANCE_AMOUNT, BU.USE_UID, null as REMARK
	, 'ORIG_SYSTEM' AS SOURCE_CODE, BB.ID_No AS SOURCE_ID, BB.UPDATED_DATE AS UPDATE_DATE, 'ORIG_USER' AS UPDATE_BY
FROM HCPODS.BANK.T_BANK_BALANCE BB
inner JOIN HCPDW.DBO.BANK_DIM_ACCOUNT_USE BU ON BU.SOURCE_CODE = 'ORIG_SYSTEM' AND BU.SOURCE_ID = BB.Bank_ID_No
WHERE 1=1
and not exists(select 1 from hcpdw.dbo.BANK_FACT_ACCOUNT_BALANCE bb2 where bb2.USE_UID = BU.USE_UID and bb2.BALANCE_DATE = CAST(BB.BALANCE_DATE AS DATE) )
;

-- 更新账户类别为BI限定的类别
select  u.ORIG_ACCOUNT_TYPE, u.ACCOUNT_TYPE, lk.MEANING 
from HCPDW.dbo.BANK_DIM_ACCOUNT_USE u
INNER join HCPDW.dbo.FIN_DIM_CUX_LOOKUPS lk on lk.LOOKUP_TYPE LIKE 'BANK_ACCOUNT_TYPE%' and lk.LOOKUP_CODE = u.ORIG_ACCOUNT_TYPE
where 1=1
and isnull(u.ACCOUNT_TYPE,'#NULL#') != isnull(lk.MEANING,'#NULL#') 
;

UPDATE U
SET  u.ACCOUNT_TYPE = lk.MEANING 
from HCPDW.dbo.BANK_DIM_ACCOUNT_USE u
INNER join HCPDW.dbo.FIN_DIM_CUX_LOOKUPS lk on lk.LOOKUP_TYPE LIKE 'BANK_ACCOUNT_TYPE%' and lk.LOOKUP_CODE = u.ORIG_ACCOUNT_TYPE
where 1=1
and isnull(u.ACCOUNT_TYPE,'#NULL#') != isnull(lk.MEANING,'#NULL#') 
;

-- 默认失效无用途的账户，以及银行
select * 
from HCPDW.dbo.BANK_DIM_BANK_ACCOUNT ba 
where 1=1
and not exists(select 1 from HCPDW.dbo.BANK_DIM_ACCOUNT_USE au where au.ACCOUNT_UID = ba.ACCOUNT_UID and au.ENABLED = 1)
;

update ba
set ba.ENABLED = 0 
from HCPDW.dbo.BANK_DIM_BANK_ACCOUNT ba 
where 1=1
and not exists(select 1 from HCPDW.dbo.BANK_DIM_ACCOUNT_USE au where au.ACCOUNT_UID = ba.ACCOUNT_UID and au.ENABLED = 1)
;


select * 
from HCPDW.dbo.BANK_DIM_BANK b 
where 1=1
and not exists(select 1 from HCPDW.dbo.BANK_DIM_BANK_ACCOUNT ba where ba.BANK_UID = b.BANK_UID and ba.ENABLED = 1)
;

update b
set b.ENABLED = 0
from HCPDW.dbo.BANK_DIM_BANK b 
where 1=1
and not exists(select 1 from HCPDW.dbo.BANK_DIM_BANK_ACCOUNT ba where ba.BANK_UID = b.BANK_UID and ba.ENABLED = 1)
;

--insert into HCPDW.DBO.BANK_DIM_BANK_ACCOUNTS
--(SOURCE_TYPE, SOURCE_ID, COMPANY, USER_NAME, FINE_USER, BANK_NAME, BANK_NAME_CN, ACCOUNT_NUMBER, CURRENCY, ACCOUNT_TYPE, BANK_AUTHORITY, BANK_LOCATION, REMARK1, REMARK2, REMARK3, UPDATED_BY, UPDATED_DATE, FNIE_UPDATE_BY, FINE_UPDATE_dATE, DW_UPDATETIME)
--select 'ORIG_SYS', t.ID_No ,t.Company
--, t.User_Name, usr.MEANING as FINE_USER_NAME
--, t.Bank_Name, NULL AS BANK_NAME_CN
--, t.Account_Number, t.Currency, t.Account_Type, t.Bank_Authority, t.Bank_Location, t.Remark1, t.Remark2, t.Remark3, t.Updated_By, t.Updated_Date
--,NULL AS FINE_UPDATE_BY, NULL AS FINE_UPDATE_DATE, t.DW_UPDATETIME
--from hcpods.bank.T_Bank t
--left join HCPDW.dbo.FIN_DIM_CUX_LOOKUPS usr on usr.LOOKUP_TYPE = 'BANK_USER_MAP' and usr.LOOKUP_CODE = t.User_Name
--where 1=1
--AND EXISTS(
--	SELECT 1 FROM HCPDW.DBO.BANK_DIM_BANK_ACCOUNTS a
--	WHERE a.ACCOUNT_NUMBER = t.Account_Number and a.CURRENCY = t.Currency and a.ACCOUNT_TYPE = t.Account_Type
--);
