-- Drop table

-- DROP TABLE HCPDW.dbo.RFS_DIM_JOBS;

CREATE TABLE HCPDW.dbo.RFS_DIM_JOBS (
	JOB_ID int IDENTITY(1,1) NOT NULL,
	JOB_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	JOB_DESC nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	LAST_UPDATE_DATE datetime2 NULL,
	LAST_UPDATED_BY nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK__RFS_DIM___2AC9D60A3F097789 PRIMARY KEY (JOB_ID),
	CONSTRAINT RFS_DIM_JOBS_UN UNIQUE (JOB_NAME)
);
CREATE UNIQUE NONCLUSTERED INDEX RFS_DIM_JOBS_UN ON HCPDW.dbo.RFS_DIM_JOBS (JOB_NAME);

-- Drop table

-- DROP TABLE HCPDW.dbo.RFS_DIM_JOB_SEQ_STEP;

CREATE TABLE HCPDW.dbo.RFS_DIM_JOB_SEQ_STEP (
	JOB_SEQ_ID int IDENTITY(1,1) NOT NULL,
	JOB_ID int NULL,
	SEQ_NO int NULL,
	STEP_ID int NULL,
	ENABLE_FLAG bit NULL,
	LAST_UPDATE_DATE datetime2 NULL,
	LAST_UPDATED_BY nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK__RFS_DIM___514781AC3FECEBBE PRIMARY KEY (JOB_SEQ_ID)
);

-- Drop table

-- DROP TABLE HCPDW.dbo.RFS_DIM_STEPS;

CREATE TABLE HCPDW.dbo.RFS_DIM_STEPS (
	STEP_ID int IDENTITY(1,1) NOT NULL,
	STEP_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	STEP_DESC nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	LAST_UPDATE_DATE datetime2 NULL,
	LAST_UPDATED_BY nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK__RFS_DIM___A8940374284E1FFF PRIMARY KEY (STEP_ID),
	CONSTRAINT RFS_DIM_STEPS_UN UNIQUE (STEP_NAME)
);
CREATE UNIQUE NONCLUSTERED INDEX RFS_DIM_STEPS_UN ON HCPDW.dbo.RFS_DIM_STEPS (STEP_NAME);

-- Drop table

-- DROP TABLE HCPDW.dbo.RFS_DIM_STEP_SEQ_TASK;

CREATE TABLE HCPDW.dbo.RFS_DIM_STEP_SEQ_TASK (
	STEP_SEQ_ID int IDENTITY(1,1) NOT NULL,
	STEP_ID int NULL,
	SEQ_NO int NULL,
	TASK_ID int NULL,
	ENABLE_FLAG bit NULL,
	LAST_UPDATE_DATE datetime2 NULL,
	LAST_UPDATED_BY nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK__RFS_DIM___9C6C90601DD7FCD2 PRIMARY KEY (STEP_SEQ_ID)
);

-- Drop table

-- DROP TABLE HCPDW.dbo.RFS_DIM_TASKS;

CREATE TABLE HCPDW.dbo.RFS_DIM_TASKS (
	TASK_ID int IDENTITY(1,1) NOT NULL,
	TASK_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	TASK_DESC nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	DATABASE_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	SCHEMA_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	TABLE_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	SQL_TEXT nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL,
	LAST_UPDATE_DATE datetime2 NULL,
	LAST_UPDATED_BY nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	CONSTRAINT PK__RFS_DIM___42E0049A5BD9A7F6 PRIMARY KEY (TASK_ID),
	CONSTRAINT RFS_DIM_TASKS_UN UNIQUE (TASK_NAME)
);
CREATE UNIQUE NONCLUSTERED INDEX RFS_DIM_TASKS_UN ON HCPDW.dbo.RFS_DIM_TASKS (TASK_NAME);

-- Drop table

-- DROP TABLE HCPDW.dbo.RFS_DIM_TABLE_CONTROL;

CREATE TABLE HCPDW.dbo.RFS_DIM_TABLE_CONTROL (
	DATABASE_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	SCHEMA_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	TABLE_NAME nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	REFRESH_BY_JOB nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL,
	DW_UPDATETIME datetime2 NULL,
	ERROR_FLAG bit NULL,
	ERROR_MSG nvarchar(MAX) COLLATE Chinese_PRC_CI_AS NULL
);
